'use strict';
names.canary='Cities II mod observer';
function citiesModCard(){return `<article class="plugin-card"><div class="plugin-top"><div class="plugin-logo">◇</div><div><h2>Cities II mod observer</h2><small>LOCAL GAME PLUGIN · EXPERIMENTAL</small></div></div><p>Connect to Unified Verified Mods for installed mod names, build evidence and loaded assemblies. Inspect compiled capabilities alongside Windows process, network and file evidence.</p><ul><li>Local UVM connection; no API key needed</li><li>Searchable mod inventory and activity details</li><li>Optional controlled canary exercise</li></ul><div class="warning-note">Windows activity belongs to the shared game process. Compiled capabilities and cooperative receipts are labelled separately; individual mod call stacks are not monitored.</div><div class="plugin-bottom"><span id="cities-mod-state" class="tag">Disabled</span><div class="inline-row"><button class="secondary" id="cities-mod-disable" data-action="cities-mod-disable">Disable</button><button class="primary" id="cities-mod-enable" data-action="cities-mod-enable">Enable plugin</button><button class="primary" id="cities-mod-open" data-page="mods">Open →</button></div></div><p class="small">Disabling disarms the test and hides its workspace. The game mod stays idle. Remove the test mod from its workspace with the game closed. Saved evidence is retained.</p></article>`;}
function citiesModUpdate(){const enabled=!!state?.data?.plugins?.citiesModObserver;$('#cities-mod-nav').hidden=!enabled;if((page==='canary'||page==='mods')&&!enabled){go('plugins');return;}if(page==='plugins'){$('#cities-mod-state').textContent=enabled?'Enabled · local':'Disabled';$('#cities-mod-disable').hidden=!enabled;$('#cities-mod-enable').hidden=enabled;$('#cities-mod-open').hidden=!enabled;}}
let canaryData=null,canaryLoading=false,canaryRefreshAt=0,canaryAlertId='',canaryPaint='';
function canaryPage(){return heading('Test the warning.','A harmless mod, a synthetic document, and independent Windows evidence.')+`<div class="canary-grid"><section class="card"><div class="card-head"><h2>Harmless Cities II test</h2><span class="tag">LOCAL · OPT IN</span></div><div class="card-body"><p>The test mod reads one synthetic document outside the game. It does not read your personal files, send data, change saves, or start other programs.</p><ol><li>Close Cities II and install the test mod.</li><li>Arm a 20-minute test and approve the Windows administrator prompt.</li><li>Start the game normally through Steam with the local mod enabled.</li><li>Review the file-read alert below. Ask chatGPT observer to explain the saved evidence.</li></ol><div class="canary-buttons"><button class="secondary" data-action="canary-install">1 · Install test mod</button><button class="primary" data-action="canary-arm">2 · Arm test</button><button class="secondary" data-action="canary-stop">Stop test</button></div><p class="card-note">The mod stays idle until a test is armed and the Windows sensor is ready. Arming also works when this mod is already loaded in a running game.</p><button class="quiet" data-action="canary-remove">Remove test mod & synthetic files</button></div></section><section class="card"><div class="card-head"><h2>What this establishes</h2></div><div class="card-body"><p><strong>Windows evidence:</strong> which process requested the canary read, and its completion status when available.</p><p><strong>Mod receipt:</strong> the test mod’s own report, matched by process lifetime and time. It is labelled as self-reported.</p><p class="warning-note">This tests the alert pipeline. It does not prove that other mods are safe or identify arbitrary mods from a managed call stack. Normal game saves, logs and settings can legitimately live outside the game folder.</p><p class="card-note">Only this synthetic file is retained by the temporary file-read sensor. The sensor stops after 20 minutes, when you stop the test, or when Observe closes normally.</p></div></section></div><section class="card"><div class="card-head"><div><h2>Latest test</h2><small id="canary-status">Reading saved evidence…</small></div><button class="secondary" data-action="canary-refresh">↻ Refresh</button></div><div class="card-body" id="canary-results"></div></section>`;}
async function loadCanary(){if(canaryLoading)return;canaryLoading=true;canaryRefreshAt=Date.now();try{canaryData=await request('canary-status');if(page==='canary')renderCanary();}catch(e){toast(e.message,true);}finally{canaryLoading=false;}}
function renderCanary(){if(!canaryData||!$('#canary-results'))return;const d=canaryData,r=d.latest;if(r){const section=$('#canary-results').closest('section');section.style.marginBottom='24px';$('.canary-grid').before(section);}$('#canary-status').textContent=r?`${date(r.started)} · ${d.sensor?.message||'Waiting for the Windows sensor'}${d.sensor?.eventsLost?' · '+d.sensor.eventsLost+' trace events lost':''}`:'No test recorded yet.';const arm=$('[data-action="canary-arm"]');arm.disabled=d.active||!!state?.data?.gaming;const key=JSON.stringify([r,d.events,d.installed,d.active,d.sensor?.state]);if(key===canaryPaint&&$('#canary-results').innerHTML)return;canaryPaint=key;
$('#canary-results').innerHTML=`<p class="card-note">Test mod: ${d.installed?'Installed':'Not installed'} · ${d.active?'Test armed': 'Not armed'}</p>${r?`<p class="path-text">Synthetic document: ${esc(r.canaryPath)}</p><p class="small muted">Expires ${date(r.expires)} · Test ${esc(r.id)}</p>`:''}${d.findings.length?'<div class="warning-note"><strong>Canary exercise: file access outside the game</strong><p>Windows recorded a read request for the synthetic document. Inspect the process and outcome below. This was a planned harmless test.</p></div>':d.events.some(e=>e.eventId===10111)?'<div class="warning-note">The mod reported a read, but no matching Windows read has been captured. Independent detection is not verified.</div>':'<p class="card-note">No Windows canary read observed. This does not mean the mod ran successfully or that other mods are safe.</p>'}<div class="table-wrap"><table class="data-table"><thead><tr><th>TIME</th><th>SOURCE</th><th>PROCESS / MOD</th><th>OBSERVATION</th></tr></thead><tbody>${d.events.map(e=>`<tr><td>${time(e.timestamp)}</td><td>${e.eventId===10110?'Windows ETW':'Mod receipt · self-reported'}</td><td>${esc(e.process)} · PID ${esc(e.data.ProcessId)}${e.data.Mod?`<small class="table-sub">${esc(e.data.Mod)}</small>`:''}</td><td>${esc(e.data.Outcome||e.detail)}${e.data.MatchingWindowsEvents?'<small class="table-sub">Matching process/time Windows evidence is present; mod identity remains self-reported.</small>':''}</td></tr>`).join('')||'<tr><td colspan="4" class="empty">Waiting for evidence.</td></tr>'}</tbody></table></div>${r?`<div class="canary-buttons"><button class="primary" data-action="canary-chat">Ask chatGPT observer</button><button class="secondary" data-action="canary-copy">Copy test evidence</button></div>`:''}<details><summary>Original records & coverage</summary><p class="card-note">${esc(d.limits)}</p><pre class="script-source">${esc(JSON.stringify(d.events,null,2))}</pre></details><p class="card-note">${d.runs.length} saved test(s). Evidence is retained across restarts and included in Overview → Export logs.</p>`;}
function updateCanary(){const e=state?.data?.plugins?.citiesModObserver?state?.data?.canaryAlert:null;let banner=$('#canary-alert');if(e){if(!banner){banner=document.createElement('div');banner.id='canary-alert';banner.className='canary-alert';banner.setAttribute('role','alert');$('#topbar').after(banner);}banner.innerHTML=`<strong>Canary exercise</strong><span>${esc(e.process)} accessed the synthetic test document. Review the Windows outcome.</span><button class="secondary compact" data-page="canary">Review evidence →</button>`;if(canaryAlertId!==e.id){canaryAlertId=e.id;toast('Canary exercise: '+e.process+' requested the synthetic file. Review Mod safety test.',true);}}else if(banner)banner.remove();if(page==='canary'&&Date.now()-canaryRefreshAt>4000)loadCanary();}
document.addEventListener('click',async event=>{const b=event.target.closest('button');if(!b)return;try{switch(b.dataset.action){
case 'cities-mod-enable':await request('cities-mod-enable');state.data.plugins.citiesModObserver=true;toast('Cities II plugin enabled. Enable the local Observe connection in UVM.');go('mods');break;
case 'cities-mod-disable':await request('cities-mod-disable');toast('Cities II plugin disabled. Test disarmed; evidence retained.');break;
case 'canary-install':await request('canary-install');toast('Test mod installed. Arm a test, then start Cities II normally through Steam.');await loadCanary();break;
case 'canary-arm':b.disabled=true;toast('Windows will ask for administrator access for the temporary file-read sensor.');try{await request('canary-arm');await loadCanary();}finally{b.disabled=false;}break;
case 'canary-stop':await request('canary-stop');await loadCanary();toast('Test disarmed. The Windows sensor will stop shortly. Evidence is saved.');break;
case 'canary-remove':toast((await request('canary-remove')).message);await loadCanary();break;
case 'canary-refresh':await loadCanary();break;
case 'canary-copy':await request('observer-copy',{text:JSON.stringify(canaryData,null,2)});toast('Test evidence copied.');break;
case 'canary-chat':if(!state.observer?.enabled||!state.observer?.hasKey){observerConfig();break;}observerChat=await request('canary-chat',{id:canaryData.latest.id});observerDraft='Did the harmless test mod access the file outside the game? Explain what Windows verified and what remains self-reported. Does this say anything about other mods?';go('observer');break;
}}catch(error){toast(error.message,true);}});
