'use strict';
names.activity='Processes';
let processData=null,processLoading=false,processSearch='',processSort='cpu',processTree=false,processDetail=null;
let appData=null,appSearch='',appPage=0,scriptTab='flows',scriptSearch='',scriptIndex=0,scriptDetail=null,storageData=null;
const shownBytes=v=>v==null?'—':sizeText(v),shortName=p=>p.split('\\').at(-1)||'Interactive / unnamed script';
activityPage=function(){return heading('Processes, in focus.','Resource usage, process ancestry and the evidence behind each app.')+`<section class="process-panel card"><div class="process-toolbar"><input id="process-search" class="search" placeholder="Search name, publisher, command line or PID" value="${esc(processSearch)}"><button class="secondary" data-action="process-tree">${processTree?'Grouped view':'Process tree'}</button><button class="primary" data-action="process-refresh">↻ Refresh</button></div><div id="process-summary" class="process-summary"></div><div class="table-wrap process-scroll"><table class="process-table"><thead><tr><th>NAME</th><th>PID</th><th><button data-process-sort="cpu">CPU ↓</button></th><th><button data-process-sort="memory">MEMORY ↓</button></th><th>PRIVATE</th><th>I/O / s</th><th>FLOWS¹</th><th>THREADS</th><th>PUBLISHER</th></tr></thead><tbody id="process-rows"><tr><td colspan="9" class="empty">Reading processes…</td></tr></tbody></table></div><div class="table-foot" id="process-foot">A still snapshot · click a process for details</div></section>`;};
async function loadProcesses(){if(processLoading)return;processLoading=true;try{processData=await request('process-snapshot');if(page==='activity')renderProcesses();}catch(e){toast(e.message,true);}finally{processLoading=false;}}
function renderProcesses(){const s=processData?.snapshot;if(!s){$('#process-rows').innerHTML='<tr><td colspan="9" class="empty">No saved process snapshot. Restore monitoring to capture one.</td></tr>';return;}const all=s.processes,rows=all.filter(p=>[p.name,p.company,p.commandLine,p.pid,p.image].join(' ').toLowerCase().includes(processSearch));
$('#process-summary').innerHTML=`<div><strong>${s.processes.length}</strong><span>Processes</span></div><div><strong>${s.cpu.toFixed(1)}<small>%</small></strong><span>Observed CPU</span></div><div><strong>${s.memoryTotal?Math.round(100*s.memoryUsed/s.memoryTotal):'—'}<small>%</small></strong><span>${shownBytes(s.memoryUsed)} / ${shownBytes(s.memoryTotal)} memory</span></div><div class="snapshot-note"><span class="tag">${s.saved?'Saved before restart':'Snapshot'}</span><span>${date(s.at)} · ${time(s.at)}</span></div>`;
const sorted=a=>a.sort((a,b)=>(b[processSort]??-1)-(a[processSort]??-1)||a.name.localeCompare(b.name));let html='';const emitted=new Set();
function row(p,depth=0){if(emitted.has(p.pid))return;emitted.add(p.pid);const flow=processData.network.find(n=>n.pid===p.pid);html+=`<tr><td><button class="process-name" data-process-pid="${p.pid}" style="padding-left:${Math.min(depth,8)*18}px">${processTree?'<span class="branch">'+(depth?'└':'◦')+'</span>':''}${appIcon(p.icon,p.name)}<span><strong>${esc(p.description||p.name)}</strong><small>${esc(p.name)}${p.status!=='Running'?' · '+esc(p.status):''}</small></span></button></td><td class="mono">${p.pid}</td><td class="resource" style="--heat:${Math.min(80,(p.cpu??0)*3)}%">${p.cpu==null?'—':p.cpu.toFixed(1)+'%'}</td><td class="resource" style="--heat:${Math.min(80,(p.memory??0)/s.memoryTotal*250)}%">${shownBytes(p.memory)}</td><td>${shownBytes(p.privateBytes)}</td><td>${p.ioRead==null?'—':shownBytes(p.ioRead+p.ioWrite)}</td><td>${flow?.flows??'—'}</td><td>${p.threads??'—'}</td><td title="${esc(p.company)}">${esc(p.company)||'—'}</td></tr>`;if(processTree)for(const c of sorted(rows.filter(c=>c.pid!==p.pid&&c.parentPid===p.pid&&(!c.started||!p.started||new Date(c.started)>=new Date(p.started)))))row(c,depth+1);}
if(processTree){for(const p of sorted(rows.filter(p=>!rows.some(x=>x.pid===p.parentPid))))row(p);for(const p of sorted(rows))row(p);}else for(const group of ['Apps','Background processes','Windows processes']){const members=sorted(rows.filter(p=>p.group===group));if(members.length){html+=`<tr class="process-group"><td colspan="9">${group} <span>${members.length}</span></td></tr>`;members.forEach(p=>row(p));}}
$('#process-rows').innerHTML=html||'<tr><td colspan="9" class="empty">No matching processes.</td></tr>';$('#process-foot').innerHTML=`${s.saved?'Historical snapshot; processes may have exited.':'Click an app for identity, modules, threads, services and tracking.'} ¹ Recorded flows in the last hour. I/O includes file and device I/O. <details><summary>Coverage</summary>${s.warnings.map(esc).join('<br>')}</details>`;}
async function openProcess(pid){const p=processData.snapshot.processes.find(p=>p.pid===pid);processDetail={row:p,details:null};modal(p.description||p.name,`<p class="card-note">Reading process details…</p>`);try{processDetail.details=await request('process-details',{pid,started:p.started});renderProcessDetails('overview');}catch(e){modal(p.name,`<div class="warning-note">${esc(e.message)}</div><pre>${esc(JSON.stringify(p,null,2))}</pre>`);}}
function renderProcessDetails(tab){const {row:p,details:d}=processDetail;const item=(name,value)=>`<div><dt>${name}</dt><dd>${esc(value??'Unavailable')}</dd></div>`;let body='';
if(tab==='overview')body=`<div class="process-identity">${appIcon(p.icon,p.name)}<div><h3>${esc(p.description||p.name)}</h3><p>${esc(p.company)||'Publisher not supplied'} · PID ${p.pid} · ${esc(d.architecture)}</p></div></div><dl class="detail-grid">${item('Executable',p.image)}${item('Command line',p.commandLine||'Unavailable')}${item('User',d.owner)}${item('Parent PID',p.parentPid)}${item('Started',p.started?new Date(p.started).toLocaleString():'Unavailable')}${item('Session / priority',p.session+' / '+p.priority)}${item('Working set / private bytes',shownBytes(p.memory)+' / '+shownBytes(p.privateBytes))}${item('Handles / threads',(p.handles??'—')+' / '+(p.threads??'—'))}${item('Signature',d.signature)}${item('SHA-256',d.sha256||'Unavailable')}</dl><p class="card-note">${esc(d.handleNote)}</p>`;
else{const entries=d[tab]||[],cols=tab==='modules'?['name','path','company','version','bytes','baseAddress']:tab==='threads'?['id','state','wait','cpuSeconds','priority','started']:['name','displayName','state','startMode'];body=`<div class="table-wrap"><table class="data-table details-table"><thead><tr>${cols.map(c=>'<th>'+esc(c)+'</th>').join('')}</tr></thead><tbody>${entries.map(x=>'<tr>'+cols.map(c=>`<td title="${esc(x[c])}">${esc(x[c]??'—')}</td>`).join('')+'</tr>').join('')||`<tr><td colspan="${cols.length}" class="empty">No accessible ${tab} recorded.</td></tr>`}</tbody></table></div>`;}
modal(p.description||p.name,`<div class="detail-tabs">${['overview','modules','threads','services'].map(t=>`<button class="${tab===t?'selected':''}" data-process-tab="${t}">${t[0].toUpperCase()+t.slice(1)}${d[t]?' · '+d[t].length:''}</button>`).join('')}</div>${body}${d.warnings.length?'<details class="card-note"><summary>Access limitations</summary>'+d.warnings.map(esc).join('<br>')+'</details>':''}`,`<button class="secondary" data-action="process-copy">Copy details</button><button class="secondary" data-action="process-network">Network activity</button><button class="primary" data-action="process-track" ${!p.image||!p.started||state.data.gaming?'disabled':''}>Track this process</button>`);}

const originalOpenTracked=openTracked;
openTracked=async function(id){await originalOpenTracked(id);if(page==='launches'){if($('#known-apps-panel'))$('#known-apps-panel').open=false;$('#launch-detail').scrollIntoView({block:'start'});}};
const originalLaunchesPage=launchesPage;
launchesPage=function(){return heading('Track an app.','Choose a running app, watch a known app’s next start, or launch a new recording.')+`<details class="card known-apps" id="known-apps-panel" open><summary class="card-head"><div><h2>Known apps</h2><p class="card-note">Apps observed on this PC. Watched paths are remembered across restarts.</p></div><button class="secondary" data-action="apps-refresh">↻ Refresh</button></summary><div class="toolbar"><input id="app-search" class="search" placeholder="Search known apps or executable paths" value="${esc(appSearch)}"><span id="app-count" class="small muted"></span></div><div class="table-wrap"><table class="data-table"><thead><tr><th>APPLICATION</th><th>STATUS</th><th>LAST OBSERVED</th><th>TRACKING</th></tr></thead><tbody id="known-app-rows"><tr><td colspan="4" class="empty">Loading known apps…</td></tr></tbody></table></div><div class="table-foot pagination"><button class="quiet" data-action="apps-prev">← Previous</button><span id="app-page"></span><button class="quiet" data-action="apps-next">Next →</button></div></details><h2 class="section-title">Launch & record · saved recordings</h2>`+originalLaunchesPage().replace(/^.*?(?=<div class="launch-layout">)/s,'');};
async function loadApps(){try{appData=await request('apps-list');if(page==='launches')renderApps();}catch(e){toast(e.message,true);}}
function renderApps(){const all=appData.apps.filter(a=>(a.name+' '+a.path).toLowerCase().includes(appSearch));appPage=Math.min(appPage,Math.max(0,Math.ceil(all.length/15)-1));$('#app-count').textContent=all.length+' known apps';$('#app-page').textContent=`${all.length?appPage*15+1:0}–${Math.min(all.length,(appPage+1)*15)} of ${all.length}`;$('#known-app-rows').innerHTML=all.slice(appPage*15,(appPage+1)*15).map(a=>{const running=appData.running.filter(p=>p.image.toLowerCase()===a.path.toLowerCase());return `<tr><td><strong>${esc(a.name)}</strong><small class="table-sub path-text" title="${esc(a.path)}">${esc(a.path)}</small></td><td><span class="tag ${running.length?'':'neutral'}">${running.length?running.length+' running':appData.paused?'Monitoring paused':'Previously seen'}</span></td><td>${date(a.lastSeen)}</td><td><div class="inline-row">${running.length>1?`<button class="secondary compact" data-pick-app="${a.id}">Choose instance (${running.length})</button>`:running.map(p=>`<button class="secondary compact" data-attach-pid="${p.pid}">Track PID ${p.pid}</button>`).join('')}<button class="${a.watch?'primary':'secondary'} compact" data-watch-app="${a.id}" data-watch-enabled="${!a.watch}">${a.watch?'✓ Watching · stop':'Watch next starts'}</button></div></td></tr>`;}).join('')||'<tr><td colspan="4" class="empty">No matching known apps. Use Launch & record below to select an executable.</td></tr>';}

scriptsPage=function(){return heading('PowerShell, in context.','A saved timeline and an overview of repeated scripts. Refresh when you want new evidence.')+`<div class="network-workspace"><aside class="network-sidebar"><div class="segmented"><button data-script-tab="flows" class="${scriptTab==='flows'?'selected':''}">⇄ Flows</button><button data-script-tab="activity" class="${scriptTab==='activity'?'selected':''}">▥ Activity</button></div><label class="field">Evidence period<select id="script-minutes">${[[5,'Last 5 minutes'],[60,'Last hour'],[1440,'Last 24 hours'],[10080,'Last 7 days'],[0,'All saved history']].map(([n,t])=>`<option value="${n}" ${scriptMinutes===n?'selected':''}>${t}</option>`).join('')}</select></label><label class="field">Search<input id="script-search" placeholder="Path or script text" value="${esc(scriptSearch)}"></label><button class="primary" data-action="refresh-scripts">↻ Refresh snapshot</button><small id="scripts-refreshed"></small><div class="network-side-note"><strong>Recorded evidence</strong><p>Flows keep time order. Activity groups identical complete script text.</p><p>Counts describe observed records; a cached script block can run again without a new text event.</p><span id="scripts-logging">${loggingControl()}</span></div></aside><div class="network-main"><div id="script-summary" class="network-summary-grid"></div><div id="script-warnings"></div><section class="card"><div class="card-head"><h2 id="script-view-title">Flows</h2></div><div class="table-wrap"><table class="data-table script-table"><thead id="script-head"></thead><tbody id="script-rows"><tr><td colspan="4" class="empty">Reading script evidence…</td></tr></tbody></table></div><div class="table-foot pagination"><button class="quiet" data-action="scripts-prev">← Previous</button><span id="script-page"></span><button class="quiet" data-action="scripts-next">Next →</button></div></section><details class="network-coverage"><summary>Sensor coverage & PowerShell 7</summary><div id="script-coverage"></div></details></div></div>`;};
loadScripts=async function(){if(scriptLoading)return;scriptLoading=true;try{const minutes=scriptMinutes;const data=await request('script-snapshot',{minutes});if(minutes===scriptMinutes){scriptData=data;if(page==='scripts')renderScripts();}}catch(e){toast(e.message,true);if(page==='scripts')$('#script-rows').innerHTML='<tr><td colspan="4" class="empty">Could not read logs. Check sensor access in Settings.</td></tr>';}finally{scriptLoading=false;}};
renderScripts=function(){if(!scriptData?.flows)return;const s=scriptData;$('#scripts-refreshed').textContent='Captured '+date(s.refreshedAt)+' · '+time(s.refreshedAt);$('#script-summary').innerHTML=`<article><span>RECORDED FLOWS</span><h2>${s.flows.length}</h2><p>Script text, invocations & module records</p></article><article><span>SCRIPT GROUPS</span><h2>${s.activity.length}</h2><p>Identical complete text grouped together</p></article><article><span>HOST PROCESSES</span><h2>${new Set(s.flows.map(f=>f.processId)).size}</h2><p>Recorded PowerShell host PIDs</p></article>`;$('#script-warnings').innerHTML=s.warnings.length?`<details class="warning-note"><summary>${s.warnings.length} capture notes</summary>${s.warnings.map(w=>'<p>'+esc(w)+'</p>').join('')}</details>`:'';$('#script-coverage').innerHTML=`<p>${esc(s.coverage.meaning)}</p><p>${s.coverage.windows.map(esc).join('<br>')}</p><p>${s.coverage.powerShell7.map(esc).join('<br>')}</p><p>${esc(s.coverage.guidance)}</p>`;
document.querySelectorAll('[data-script-tab]').forEach(b=>b.classList.toggle('selected',b.dataset.scriptTab===scriptTab));const flows=scriptTab==='flows';$('#script-view-title').textContent=flows?'Flows':'Script Activity';const rows=(flows?s.flows:s.activity).filter(r=>(r.path+' '+(r.text||'')+' '+r.recordType).toLowerCase().includes(scriptSearch));scriptIndex=Math.min(scriptIndex,Math.max(0,Math.ceil(rows.length/40)-1));$('#script-head').innerHTML=flows?'<tr><th>OBSERVED</th><th>SCRIPT</th><th>RECORD TYPE</th><th>HOST PID</th></tr>':'<tr><th>SCRIPT</th><th>RECORDS</th><th>FIRST / LAST SEEN</th><th>HOSTS</th></tr>';$('#script-rows').innerHTML=rows.slice(scriptIndex*40,(scriptIndex+1)*40).map(r=>flows?`<tr><td class="mono">${date(r.lastSeen)}<small class="table-sub">${time(r.lastSeen)}</small></td><td><button class="script-title" data-script-flow="${r.id}">${esc(shortName(r.path))}</button><small class="table-sub" title="${esc(r.path)}">${esc(r.path)||esc(r.text.slice(0,100))}</small></td><td><span class="tag">${esc(r.recordType)}</span>${r.text&&!r.complete?'<small class="table-sub">Partial text</small>':''}</td><td>${esc(r.processId)||'—'}</td></tr>`:`<tr><td><button class="script-title" data-script-flow="${r.representative}">${esc(shortName(r.path))}</button><small class="table-sub">${r.paths.length} path(s) · ${esc(r.recordType)}</small></td><td>${r.count}</td><td>${date(r.firstSeen)}<small class="table-sub">${date(r.lastSeen)}</small></td><td>${r.pids.length}</td></tr>`).join('')||'<tr><td colspan="4" class="empty">No matching records in this period. Try a wider period or inspect sensor coverage.</td></tr>';$('#script-page').textContent=`${rows.length?scriptIndex*40+1:0}–${Math.min(rows.length,(scriptIndex+1)*40)} of ${rows.length}`;};
async function openScriptFlow(id){scriptDetail=await request('script-detail',{id});const f=scriptDetail.flow;modal(shortName(f.path),`<div class="script-detail-meta"><span class="tag">${esc(f.recordType)}</span><span>${date(f.lastSeen)} · PID ${esc(f.processId)}</span><span>${scriptDetail.occurrences.length} matching record(s)</span></div><p class="path-text">${esc(f.path)||'No file path recorded'}</p><p class="card-note">${f.text?(f.complete?'Complete logged script text.':'Partial logged script text; fragments are missing.'):'This record has no script text.'} Script intent does not prove each statement completed.</p><pre class="script-source">${esc(f.text)||'Inspect the original event for invocation or module details.'}</pre><details><summary>Original evidence</summary><pre>${esc(JSON.stringify(scriptDetail.evidence,null,2))}</pre></details>`,`${state.observer?.enabled&&state.observer?.hasKey?'<button class="primary" data-action="script-summary">Summarize & review logging</button>':'<button class="secondary" data-action="observer-config">Set up chatGPT observer</button>'}`);}

const oldOverviewPage=overviewPage;
overviewPage=function(){return oldOverviewPage().replace('FOLLOW AN APP FROM THE START','TRACK AN APP').replace('What does this game do?','Which app would you like to track?').replace('Launch & observe','Track an app').replace('Launch a game or installer through Observe.','Choose a running or previously observed app, or launch a game or installer through Observe.')+`<section class="card storage-card"><div class="card-head"><div><h2>Local log storage</h2><p class="card-note">Saved evidence stays here between restarts.</p></div><button class="secondary" data-action="storage-refresh">↻ Refresh</button></div><div class="card-body" id="storage-info"><p class="card-note">Reading saved storage…</p></div><div class="storage-actions"><button class="primary" data-action="storage-export">Export logs…</button><button class="secondary danger" data-action="storage-delete">Delete saved logs…</button></div></section>`;};
async function loadStorage(){try{storageData=await request('storage-usage');if(page==='overview')renderStorage();}catch(e){toast(e.message,true);}}
function renderStorage(){const s=storageData;$('#storage-info').innerHTML=`<div class="storage-total"><strong>${shownBytes(s.bytes)}</strong><span>on this computer · refreshed ${time(s.at)}</span></div><div class="storage-categories">${s.categories.map(c=>`<div><span>${esc(c.name.replaceAll('-',' '))}</span><strong>${shownBytes(c.bytes)}</strong><small>${c.files} files</small></div>`).join('')}</div><p class="card-note">${esc(s.scope)}</p><p class="small path-text">${esc(s.path)}</p>`;}
document.addEventListener('input',e=>{if(e.target.id==='process-search'){processSearch=e.target.value.toLowerCase();if(processData)renderProcesses();}if(e.target.id==='app-search'){appSearch=e.target.value.toLowerCase();appPage=0;if(appData)renderApps();}if(e.target.id==='script-search'){scriptSearch=e.target.value.toLowerCase();scriptIndex=0;if(scriptData)renderScripts();}});
document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;try{
if(b.dataset.processPid){await openProcess(Number(b.dataset.processPid));return;}if(b.dataset.processSort){processSort=b.dataset.processSort;renderProcesses();return;}if(b.dataset.processTab){renderProcessDetails(b.dataset.processTab);return;}
if(b.dataset.scriptTab){scriptTab=b.dataset.scriptTab;scriptIndex=0;renderScripts();return;}if(b.dataset.scriptFlow){await openScriptFlow(b.dataset.scriptFlow);return;}
if(b.dataset.watchApp){await request('app-watch',{id:b.dataset.watchApp,enabled:b.dataset.watchEnabled==='true'});await loadApps();toast(b.dataset.watchEnabled==='true'?'App path saved. Running and future instances will be tracked while monitoring is on.':'Future automatic tracking stopped. Existing recordings are retained.');return;}
if(b.dataset.pickApp){const a=appData.apps.find(a=>a.id===b.dataset.pickApp);modal('Choose an instance of '+a.name,'<div class="instance-list">'+appData.running.filter(p=>p.image.toLowerCase()===a.path.toLowerCase()).map(p=>'<div><span>PID '+p.pid+' · '+(p.started?date(p.started):'Creation time unavailable')+'</span><button class="primary" data-attach-pid="'+p.pid+'">Track this instance</button></div>').join('')+'</div>');return;}
if(b.dataset.attachPid){const p=appData.running.find(p=>p.pid===Number(b.dataset.attachPid));const run=await request('tracked-attach',{pid:p.pid,started:p.started,path:p.image});$('#modal').classList.add('hidden');await loadLaunches();await openTracked(run.id);return;}
switch(b.dataset.action){case 'process-refresh':await loadProcesses();break;case 'process-tree':processTree=!processTree;b.textContent=processTree?'Grouped view':'Process tree';if(processData)renderProcesses();break;case 'process-copy':await request('observer-copy',{text:JSON.stringify(processDetail,null,2)});toast('Process details copied');break;
case 'process-network':networkApp=processDetail.row.image;networkSearch='';networkMinutes=60;$('#modal').classList.add('hidden');go('network');break;
case 'process-track':const p=processDetail.row;const run=await request('tracked-attach',{pid:p.pid,started:p.started,path:p.image});$('#modal').classList.add('hidden');trackedView=await request('tracked-open',{id:run.id});go('launches');break;
case 'apps-refresh':await loadApps();break;case 'apps-prev':appPage=Math.max(0,appPage-1);renderApps();break;case 'apps-next':appPage++;renderApps();break;
case 'scripts-prev':scriptIndex=Math.max(0,scriptIndex-1);renderScripts();break;case 'scripts-next':scriptIndex++;renderScripts();break;
case 'script-summary':observerChat=await request('script-chat',{id:scriptDetail.flow.id});observerMinutes=60;observerDraft=observerChat.messages[0].text;$('#modal').classList.add('hidden');go('observer');break;
case 'storage-refresh':await loadStorage();break;case 'storage-export':const result=await request('storage-export');if(!result.cancelled)toast('Export saved: '+result.path);break;
case 'storage-delete':modal('Delete Observe’s saved logs',`<div class="warning-note">Deletes saved event journals, recordings, chat history and known-app history (${shownBytes(storageData?.bytes)} at the last refresh). Export first if you need a copy. Finish all recordings before deletion.</div><p class="card-note">API keys, preferences, sensor restoration backups and Windows event logs are kept. New monitoring continues; records still retained by Windows can appear again when queried.</p><label class="field">Type DELETE to confirm<input id="storage-confirm" autocomplete="off"></label>`,'<button class="primary danger" data-action="storage-delete-confirm">Delete logs</button>');break;
case 'storage-delete-confirm':storageData=await request('storage-delete',{confirmation:$('#storage-confirm').value});observerChat=null;trackedView=null;processData=null;scriptData=null;networkSnapshot=null;$('#modal').classList.add('hidden');if(page==='overview')renderStorage();toast('Saved Observe logs deleted. New monitoring continues.');break;
}
}catch(error){toast(error.message,true);}});
