'use strict';
names.mods='Cities II mods';
let modRequestKey='';
let modsData=null,modsLoading=false,modsAt=0,modSearch='',modCodeOnly=true,modLoadedOnly=false,modFilterSaving=false;
function modsPage(){return heading('Your city. Its mods.','Build evidence and local activity, connected through Unified Verified Mods.',`<button class="secondary" data-page="canary">Controlled canary test →</button>`)+`<div class="mod-connection card"><div><span id="mod-connection" class="tag warn">Connecting…</span><p id="mod-notice" class="card-note"></p></div><button class="secondary" data-action="mods-refresh">↻ Refresh</button></div><div class="toolbar"><input class="search" id="mod-search" placeholder="Find a mod by name, version or Paradox ID…" value="${esc(modSearch)}"><span id="mod-count" class="muted small"></span></div><details class="mod-filters"><summary>Filters</summary><label><input id="mod-code-only" type="checkbox" ${modCodeOnly?'checked':''}> Code mods only</label><label><input id="mod-loaded-only" type="checkbox" ${modLoadedOnly?'checked':''}> Loaded mods only</label></details><div id="mod-coverage" class="warning-note"></div><section class="card mod-table"><div class="table-wrap"><table class="data-table"><thead><tr><th>MOD / VERSION</th><th>GAME INVENTORY</th><th>LAST BUILD SCAN</th><th>COMPILED REFERENCES</th><th>PARTICIPATE</th></tr></thead><tbody id="mod-rows"></tbody></table></div></section><div class="info-banner">UVM connects automatically; allow “Connect to Observe on this PC” in Cities II → Options → Unified Verified Mods → Scan. This connection is local. AI description-alignment assessment is a future feature.</div>`;}
async function loadMods(){if(modsLoading)return;modsLoading=true;modsAt=Date.now();try{modsData=await request('cities-mod-inventory');if(page==='mods')renderMods();}catch(e){toast(e.message,true);}finally{modsLoading=false;}}
function modIcon(m){const icon=m.icon||'';return /^data:image\/png;base64,[A-Za-z0-9+/=]+$/.test(icon)&&icon.length<100000?`<img class="mod-icon" src="${icon}" alt="">`:`<span class="mod-icon mod-fallback" aria-hidden="true">${esc((m.name||'M').slice(0,1).toUpperCase())}</span>`;}
function modBuild(m){const b=m.build||{},ok=b.status==='REPRODUCED';return `<span class="tag ${ok?'':'warn'}">${ok?'✓':'⚠'} ${esc(b.status||'NOT_SCANNED')}</span>`;}
function canInformModder(m){return /^[1-9][0-9]{0,18}$/.test(String(m.mod_id||''));}
function modRequestText(m){return `Hi! Thanks for making ${m.name}. Would you consider adding Unified Verified Mods (UVM) build evidence for this mod?

UVM lets players compare their downloaded files with signed builds from public source. It shows which GitHub accounts reproduced a build; this is not a security audit or a guarantee of safety.

For authors: keep the exact release source public on GitHub, add a small uvm.json describing your existing project/build command and all package outputs, then use the UVM CLI to publish a signed manifest for that commit. Upload the same package to Paradox without changing the recorded files.

Other modders can inspect the source, check out that commit, rebuild with the recorded toolchain, compare the hashes and sign their own result. No DLLs need to be uploaded to the UVM registry.

Author and verifier guide: https://vezit.net/#participate
Full commands: https://github.com/vicmrp/CS2-UnifiedVerifiedMods/blob/main/USER_GUIDE.md

Thank you for considering it!`;}
function modRequestRow(m){return `<tr class="mod-request-row"><td colspan="5"><section class="mod-request"><h3>Invite the author to add build evidence</h3><p>1. Review and copy this request. 2. Open the mod’s Paradox page. 3. Paste it in the author’s comments if appropriate. Please avoid duplicate requests.</p><label>Suggested message<textarea readonly rows="13">${esc(modRequestText(m))}</textarea></label><div class="toolbar"><button class="secondary" data-mod-copy="${esc(m.key)}">Copy request</button><button class="primary" data-mod-goto="${esc(m.key)}">Go to mod on Paradox ↗</button></div><small>Nothing is posted automatically. No local paths, activity logs or personal data are included.</small></section></td></tr>`;}
function renderMods(){if(!modsData||!$('#mod-rows'))return;const d=modsData,inventory=d.inventory,mods=inventory?.mods||[];if(d.filters&&!modFilterSaving){modCodeOnly=d.filters.codeOnly;modLoadedOnly=d.filters.loadedOnly;$('#mod-code-only').checked=modCodeOnly;$('#mod-loaded-only').checked=modLoadedOnly;}$('#mod-connection').textContent=d.connected?'✓ UVM connected':'⚠ UVM not connected';$('#mod-connection').className='tag '+(d.connected?'':'warn');$('#mod-notice').textContent=d.notice+(inventory?' · Snapshot '+date(inventory.generated_at):'');$('#mod-coverage').textContent=(d.monitoring?'':'Windows monitoring is paused. ')+d.coverage+(inventory?.warning?' '+inventory.warning:'');const filtered=mods.filter(m=>(!modCodeOnly||m.is_code!==false)&&(!modLoadedOnly||m.loaded)).filter(m=>JSON.stringify([m.name,m.mod_id,m.version,m.availability]).toLowerCase().includes(modSearch.toLowerCase()));$('#mod-count').textContent=`${filtered.length} / ${mods.length} packages · ${mods.filter(m=>m.loaded).length} loaded · Scan ${inventory?.scan_at?date(inventory.scan_at):'not run'}`;$('#mod-rows').innerHTML=filtered.map(m=>`<tr><td><button class="mod-open" data-mod-key="${esc(m.key)}">${modIcon(m)}<span><strong>${esc(m.name)}</strong><small>${esc(m.version||'Version unknown')} · ${esc(m.mod_id?'Paradox '+m.mod_id:'Local mod')}</small></span></button></td><td>${esc(m.availability||'Unknown')}<small>${esc(m.folder||'')}</small></td><td>${modBuild(m)}</td><td>${[...new Set((m.capabilities||[]).filter(c=>c.category!=='coverage').map(c=>c.category))].map(c=>`<span class="mod-capability">${esc(c)}</span>`).join('')||'<span class="muted">None found</span>'}<small>Possible capability only</small></td><td>${canInformModder(m)?`<button class="secondary" data-mod-inform="${esc(m.key)}" aria-expanded="${modRequestKey===m.key}">Inform the modder</button>`:'<span class="muted">Local package</span>'}</td></tr>${modRequestKey===m.key&&canInformModder(m)?modRequestRow(m):''}`).join('')||`<tr><td colspan="5"><div class="empty">${inventory?'No matching mods.':'Start the game with UVM 0.5.0 or later and enable its local Observe connection.'}</div></td></tr>`;}
async function modDetails(key){const d=await request('cities-mod-details',{key}),m=d.mod,b=m.build||{};modal(m.name||'Mod details',`<div class="mod-detail-header">${modIcon(m)}<div>${modBuild(m)}<p>${esc(m.availability||'')} · ${esc(m.version||'Version unknown')} · ${d.connected?'UVM connected':'Snapshot offline'}</p></div></div><p>${esc(m.description||'No cached description available.')}</p><p class="warning-note">${esc(d.coverage)}</p><div class="mod-facts"><strong>Build evidence</strong><p>${esc(b.reason||'Not scanned')}<br>Signed matching account(s): ${esc((b.verified_by||[]).join(', ')||'None')}<br>Scanned: ${d.scanAt?date(d.scanAt):'Not scanned'}</p><strong>Game process</strong><p>PID ${d.pid} · started ${date(d.processStart)}<br>${esc(m.path||'')}</p><strong>Loaded assemblies / state</strong><pre>${esc((m.modules||[]).map(x=>`${x.name} · ${x.state}\n${x.path}${x.load_error?'\n'+x.load_error:''}`).join('\n\n')||'No loaded module reported for this package.')}</pre></div><h3>Compiled file, network and process calls</h3><p class="card-note">These calls exist in the compiled DLL; they may never run. This is not a source-code audit.</p><div class="mod-evidence-list">${(m.capabilities||[]).map(c=>`<div><span class="tag">${esc(c.category)}</span> <strong>${esc(c.api)}</strong><small>${esc(c.assembly||'')} · ${esc(c.caller||'')}</small></div>`).join('')||'<p>No supported direct references found. Indirect or native calls can be missed.</p>'}</div><h3>Cooperative mod activity</h3><p class="card-note">Reported by the mod through UVM. This is not independent proof.</p><div class="mod-evidence-list">${d.receipts.map(e=>`<div><strong>${esc(e.category)} · ${esc(e.operation)}</strong><p>${esc(e.target)}</p><small>${date(e.at)}</small></div>`).join('')||'<p>No cooperative receipts. Existing mods do not automatically report every action.</p>'}</div><h3>Shared game process and descendant activity</h3><p class="card-note">${m.loaded?'Shown for context for every loaded mod; these events do not identify the responsible mod.':'This package is not reported as loaded; game activity is not attached to it.'} ${d.monitoring?'':'Windows collectors are paused.'}</p><div class="mod-evidence-list">${d.sharedGameActivity.map(e=>`<div><strong>${esc(e.kind)} · ${esc(e.process)}</strong><p>${esc(e.detail)}</p><small>${date(e.timestamp)} · ${esc(e.category)}</small></div>`).join('')||'<p>No matching retained Windows evidence. This does not prove absence of activity.</p>'}</div>`);}
document.addEventListener('input',e=>{if(e.target.id==='mod-search'){modSearch=e.target.value;renderMods();}});
document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;try{if(b.dataset.modKey)await modDetails(b.dataset.modKey);if(b.dataset.modInform){modRequestKey=modRequestKey===b.dataset.modInform?'':b.dataset.modInform;renderMods();}if(b.dataset.modCopy){const m=modsData?.inventory?.mods.find(m=>m.key===b.dataset.modCopy);if(m&&canInformModder(m)){await request('observer-copy',{text:modRequestText(m)});toast('Request copied. Review it before posting on Paradox.');}}if(b.dataset.modGoto)await request('cities-mod-open-page',{key:b.dataset.modGoto});if(b.dataset.action==='mods-refresh')await loadMods();}catch(error){toast(error.message,true);}});
function updateMods(){if(page==='mods'&&Date.now()-modsAt>5000)loadMods();}

document.addEventListener('change',async e=>{if(!['mod-code-only','mod-loaded-only'].includes(e.target.id))return;modCodeOnly=$('#mod-code-only').checked;modLoadedOnly=$('#mod-loaded-only').checked;modFilterSaving=true;$('#mod-code-only').disabled=$('#mod-loaded-only').disabled=true;try{const filters=await request('cities-mod-filters',{codeOnly:modCodeOnly,loadedOnly:modLoadedOnly});if(modsData)modsData.filters=filters;}catch(error){toast(error.message,true);}finally{modFilterSaving=false;if($('#mod-code-only'))$('#mod-code-only').disabled=$('#mod-loaded-only').disabled=false;renderMods();}});
