'use strict';
let observerChat=null,observerChats=[],observerDraft='',observerMinutes=60,observerSending=false,observerStream='',observerStreamId='',observerError='',observerFilter='',observerErrorLog='';
const observerExample='I just opened "C:\\Users\\ExampleUser\\Documents\\Games\\Warcraft III\\Frozen Throne.exe". Please tell me what this program did to my computer.';
function observerPluginCard(){return `<article class="plugin-card observer-plugin"><div class="plugin-top"><div class="plugin-logo observer-logo">✳</div><div><h2>chatGPT observer</h2><small>YOUR WINDOWS EVIDENCE, EXPLAINED</small></div></div><p>A familiar chat workspace for understanding what programs did on your computer, with saved conversations and recorded evidence.</p><ul><li>Your own OpenAI API key required</li><li>Chat history saved on this PC</li><li>Saved key protected by Windows for your user</li></ul><div class="warning-note">Sending a message shares your question, recent chat context and relevant evidence with OpenAI. API charges apply.</div><div class="plugin-bottom"><span id="observer-plugin-state" class="tag">API key required</span><div class="inline-row"><button class="secondary" data-action="observer-remove" id="observer-remove">Remove</button><button class="primary" data-action="observer-config">Configure ↗</button></div></div><p class="small"><button class="card-link" data-page="observer">Open chatGPT observer →</button></p></article>`;}
function observerPluginUpdate(){const p=state.observer;$('#observer-plugin-state').textContent=p.enabled&&p.hasKey?'Configured':'API key required';$('#observer-remove').disabled=!p.enabled&&!p.hasKey;}
function observerConfig(){modal('Set up chatGPT observer',`<p class="card-note">Connect your OpenAI API key to ask about recorded activity. Your key is encrypted by Windows and never included in chat evidence.</p><label class="field">OpenAI API key<input id="observer-key" type="password" autocomplete="off" placeholder="${state.observer.hasKey?'Leave blank to keep your saved key':'Enter your OpenAI API key'}"></label><label class="field">OpenAI model<select id="observer-model" aria-label="OpenAI model">${observerModelOptions()}</select><small id="observer-model-info">${observerModelInfo(state.observer.model)}</small></label><div class="warning-note">Sending a message shares relevant event details and chat context with OpenAI. Redaction is best effort. API usage is billed separately from ChatGPT subscriptions.</div><p class="card-note">Chat history stays in Observe on this PC. It does not sync with chatgpt.com.</p>`,`<button class="primary" data-action="observer-save">Save & enable plugin</button>`);}
function observerPage(){return `<div class="observer-shell"><aside class="chat-history"><div class="chat-history-top"><span class="eyebrow">YOUR CONVERSATIONS</span><button class="new-chat" data-action="observer-new">＋ <span>New chat</span><span class="compose-icon">↗</span></button><input id="chat-search" class="chat-search" aria-label="Search chats" placeholder="Search chats" value="${esc(observerFilter)}"></div><div id="chat-list" class="chat-list"></div><div class="chat-history-bottom"><span>◇ &nbsp; History saved on this PC</span><button class="quiet" data-action="observer-config">⚙ &nbsp; Plugin settings</button></div></aside><section class="chat-main"><div class="chat-top"><div><h2>chatGPT observer <select id="chat-model" aria-label="Observer model">${observerModelOptions()}</select></h2><span id="chat-subject" class="chat-subject"></span></div><div class="inline-row"><button class="quiet" data-action="observer-rename" aria-label="Rename chat" title="Rename chat">Rename</button><button class="quiet" data-action="observer-delete" aria-label="Delete chat" title="Delete chat">Delete</button></div></div><div class="chat-scroll" id="chat-scroll"><div id="chat-messages" class="chat-messages" aria-live="polite"></div></div><div class="chat-compose-wrap"><div id="chat-setup" class="chat-setup"></div><div id="chat-error" class="chat-error" role="alert"></div><form id="chat-form" class="chat-compose"><textarea id="chat-input" aria-label="Message chatGPT observer" rows="2" maxlength="8000" placeholder="Ask what a program did to your computer…">${esc(observerDraft)}</textarea><div class="chat-compose-bottom"><div class="chat-options"><label><span class="sr-only">Evidence period</span><select id="chat-period" aria-label="Evidence period"><option value="15">Last 15 minutes</option><option value="60">Last hour</option><option value="1440">Last 24 hours</option><option value="10080">Last 7 days</option><option value="0">All retained logs</option></select></label><label class="refresh-evidence"><input id="chat-refresh" type="checkbox">Refresh evidence</label></div><button class="chat-send" id="chat-send" type="submit" aria-label="Send message" title="Send message">↑</button><button class="chat-stop hidden" id="chat-stop" type="button" data-action="observer-stop" aria-label="Stop response">■</button></div></form><p class="chat-disclosure">Send shares relevant evidence and chat context with OpenAI. API charges apply. Answers are limited to recorded activity.</p></div></section></div>`;}
function observerWelcome(){return `<div class="chat-welcome"><div class="observer-orbit">✳</div><div class="eyebrow">ASK. UNDERSTAND. FOLLOW THE EVIDENCE.</div><h1>What happened on your PC?</h1><p>Ask about a program you opened.<br>We’ll connect your question to the activity Windows recorded.</p><div class="chat-suggestions"><button data-action="observer-example"><span>↗</span><strong>Explain a program</strong><small>I just opened Frozen Throne.exe.<br>What did it do to my computer?</small></button><button data-action="observer-script-example"><span>⌘</span><strong>Understand a script</strong><small>What files and registry keys<br>did my PowerShell script change?</small></button></div><span class="chat-welcome-note">Process activity · File & registry changes · Network connections</span></div>`;}
function observerMarkdown(text,payload=null){
  // Escape every model/event character first. No model HTML, images or executable links.
  let safe=esc(text);const codes=[];const ids=new Set(observerEvents(payload).flatMap(e=>[e.id,e.citationId].filter(Boolean).map(esc)));
  safe=safe.replace(/```[^\n]*\n([\s\S]*?)```/g,(_,v)=>{codes.push('<pre class="chat-code"><code>'+v+'</code></pre>');return '\u0000'+(codes.length-1)+'\u0000';});
  safe=safe.replace(/`([^`\n]+)`/g,'<code>$1</code>').replace(/\*\*([^*\n]+)\*\*/g,'<strong>$1</strong>');
  safe=safe.replace(/^#{1,4} (.+)$/gm,'<h3>$1</h3>').replace(/^[-*] (.+)$/gm,'<div class="chat-bullet">• <span>$1</span></div>');
  safe=safe.replace(/\[event:([^\]\r\n]+)\]/g,(match,id)=>ids.has(id)?'<button class="evidence-link" data-observer-event="'+id+'">↗ evidence</button>':payload===null?match:'<span class="unverified-citation" title="This reference is not in the supplied evidence">'+match+' · unverified</span>');
  safe=safe.replace(/\n/g,'<br>').replace(/\u0000(\d+)\u0000/g,(_,i)=>codes[Number(i)]);
  return safe;
}
function observerEvidence(payload){try{const p=JSON.parse(payload);return `<details class="chat-evidence"><summary>◇ ${p.coverage.included} recorded events · Evidence snapshot</summary><p>${esc(p.focus||'No program identified')}<br>${p.start?esc(new Date(p.start).toLocaleString()):'Period unavailable'} — ${p.end?esc(new Date(p.end).toLocaleString()):''}</p>${(p.coverage.warnings||[]).map(w=>'<p>'+esc(w)+'</p>').join('')}<details><summary>View exact evidence shared with OpenAI</summary><pre>${esc(payload)}</pre></details></details>`;}catch{return '';}}
function observerEvidenceGap(payload){try{const p=JSON.parse(payload);if(!p.focus||p.events?.length)return '';const hints=p.focus.toLowerCase().endsWith('.ps1')?(state?.data?.sensors?.powerShellSessionWarnings||[]):[];return '<div class="chat-evidence-gap" role="note"><strong>Observe could not link recorded activity to this run.</strong><p>This does not mean the program or script did not run. An empty snapshot cannot establish what it changed.</p>'+hints.map(w=>'<p>Current sensor check: '+esc(w)+'</p>').join('')+'<p>Sending another message automatically checks for fresh evidence when the previous snapshot is empty.</p></div>';}catch{return '';}}
function observerEvents(payload){try{return JSON.parse(payload)?.events||[];}catch{return [];}}
function observerSnapshot(messageId){let snapshot='';for(const m of observerChat?.messages||[]){if(m.evidence)snapshot=m.evidence;if(m.id===messageId)return snapshot;}return '';}
function observerProblem(m){return m.status==='error'?(m.errorMessage??m.text):m.status==='pending'?'This answer did not finish. The last saved text is shown above. Send another message to try again.':'';}
function observerBody(m){return m.status==='error'&&m.errorMessage==null?'':m.text;}
function observerMessages(){
  const el=$('#chat-messages');if(!el)return;let snapshot='';
  el.innerHTML=observerChat?.messages?.length?observerChat.messages.map(m=>{
    if(m.evidence)snapshot=m.evidence;
    const assistant=m.role==='assistant',body=assistant?observerBody(m):m.text,problem=assistant?observerProblem(m):'';
    return `<article data-message-id="${esc(m.id)}" class="chat-message ${assistant?'from-observer':'from-user'} ${problem?'message-error':''}"><div class="message-label">${assistant?'✳ &nbsp; chatGPT observer':'You'}<span>${time(m.at)}</span></div>${assistant&&snapshot?observerEvidenceGap(snapshot):''}${body?'<div class="message-body">'+(assistant?observerMarkdown(body,snapshot):esc(body).replace(/\n/g,'<br>'))+'</div>':''}${problem?'<div class="message-problem" role="alert">'+esc(problem)+'</div>':''}${assistant&&snapshot?observerEvidence(snapshot):''}${assistant?`<div class="message-actions"><button class="message-copy quiet" data-copy-message="${esc(m.id)}">Copy</button>${m.status==='error'?`<button class="error-log-button" data-error-message="${esc(m.id)}">View error log ↗</button>`:''}</div>`:''}</article>`;
  }).join(''):observerWelcome();
  if(observerSending)el.insertAdjacentHTML('beforeend',`<article class="chat-message from-observer"><div class="message-label">✳ &nbsp; chatGPT observer<span>Reviewing recorded evidence</span></div><div id="chat-stream" class="message-body">${observerStream?observerMarkdown(observerStream):'<span class="thinking-dots">● ● ●</span>'}</div></article>`);
  observerUpdate();
}
function observerHistory(){const el=$('#chat-list');if(!el)return;el.innerHTML=observerChats.filter(c=>c.title.toLowerCase().includes(observerFilter.toLowerCase())).map(c=>`<button class="chat-history-item ${observerChat?.id===c.id?'selected':''}" data-chat-id="${esc(c.id)}" title="${esc(c.title)}"><span>${esc(c.title)}</span><small>${date(c.updated)}</small></button>`).join('')||'<div class="chat-history-empty">Your chats will appear here.</div>';}
async function observerLoad(){observerMessages();observerHistory();$('#chat-period').value=String(observerMinutes);try{observerChats=await request('observer-list');if(page==='observer')observerHistory();}catch(e){toast(e.message,true);}}
function observerUpdate(){if(page!=='observer'||!$('#chat-input'))return;const connected=state.observer.enabled&&state.observer.hasKey,paused=state.data.gaming;$('#chat-model').value=state.observer.model;$('#chat-model').disabled=observerSending||state.busy||!connected;$('#chat-subject').textContent=(observerChat?.subject||'Grounded in your local Windows evidence')+(observerChat?.trackedRunId?' · Saved recording · refreshed on Send':'');$('#chat-setup').innerHTML=!connected?'<span>Add your OpenAI API key to start a conversation.</span><button class="secondary" data-action="observer-config">Set up plugin ↗</button>':paused?'<span>Observer is paused in performance mode.</span>':'';$('#chat-setup').classList.toggle('hidden',connected&&!paused);$('#chat-error').textContent=observerError;$('#chat-send').disabled=!connected||paused||state.busy||observerSending||!$('#chat-input').value.trim();$('#chat-send').classList.toggle('hidden',observerSending);$('#chat-stop').classList.toggle('hidden',!observerSending);$('#chat-input').disabled=observerSending;$('#chat-period').disabled=observerSending||!!observerChat?.trackedRunId;$('#chat-refresh').disabled=observerSending||!!observerChat?.trackedRunId;document.querySelectorAll('[data-action="observer-new"],[data-action="observer-delete"],[data-action="observer-rename"],[data-chat-id]').forEach(b=>b.disabled=observerSending);}
function observerBottom(){const el=$('#chat-scroll');if(el)el.scrollTop=el.scrollHeight;}
async function observerSend(){if(observerSending)return;const question=$('#chat-input').value.trim();if(!question)return;observerDraft=question;observerError='';observerMinutes=Number($('#chat-period').value);const refresh=$('#chat-refresh').checked;const original=observerChat;const id=observerChat?.id||'';observerChat=observerChat?{...observerChat,messages:[...observerChat.messages]}:{id:'',messages:[]};observerChat.messages.push({id:'sending',role:'user',text:question,at:new Date().toISOString(),status:'complete'});observerSending=true;observerStream='';observerStreamId='';$('#chat-input').value='';observerMessages();observerBottom();try{observerChat=await request('observer-send',{id,question,minutes:observerMinutes,refresh});observerDraft='';}catch(e){if(observerStream){observerChat.messages.push({id:'interrupted-'+Date.now(),role:'assistant',text:observerStream,at:new Date().toISOString(),status:'error',errorMessage:'Observe lost the response connection: '+e.message+' The text received is retained above.',error:{stage:'bridge',code:'connection_lost',message:e.message}});observerDraft='';}else{observerChat=original;observerError=e.message;}}finally{observerSending=false;if(page==='observer'){$('#chat-input').value=observerDraft;observerMessages();observerBottom();await observerLoad();}}}
window.chrome.webview.addEventListener('message',event=>{const m=event.data;if(m.type!=='observer-delta'||!observerSending)return;observerStreamId=m.chatId;if(observerChat&&!observerChat.id)observerChat.id=m.chatId;observerStream+=m.delta;if(page==='observer'&&$('#chat-stream')){const nearBottom=$('#chat-scroll').scrollHeight-$('#chat-scroll').scrollTop-$('#chat-scroll').clientHeight<140;$('#chat-stream').innerHTML=observerStream?observerMarkdown(observerStream):'<span class="thinking-dots">● ● ●</span>';if(nearBottom)observerBottom();}});
document.addEventListener('submit',e=>{if(e.target.id==='chat-form'){e.preventDefault();if(!$('#chat-send').disabled)observerSend();}});
document.addEventListener('keydown',e=>{if(e.target.id==='chat-input'&&e.key==='Enter'&&!e.shiftKey&&!e.isComposing){e.preventDefault();if(!$('#chat-send').disabled)observerSend();}});
document.addEventListener('input',e=>{if(e.target.id==='chat-input'){observerDraft=e.target.value;observerUpdate();}if(e.target.id==='chat-search'){observerFilter=e.target.value;observerHistory();}});
document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;try{
if(b.dataset.chatId){observerChat=await request('observer-open',{id:b.dataset.chatId});observerMinutes=observerChat.minutes;observerDraft='';render();await observerLoad();observerBottom();return;}
if(b.dataset.observerEvent){const found=observerEvents(observerSnapshot(b.closest('[data-message-id]')?.dataset.messageId)).find(x=>x.id===b.dataset.observerEvent||x.citationId===b.dataset.observerEvent);if(found)jsonModal('Recorded event · shared snapshot',found);else toast('This event is not present in the shared snapshot.',true);return;}
if(b.dataset.errorMessage){const m=observerChat.messages.find(x=>x.id===b.dataset.errorMessage);observerErrorLog=JSON.stringify(m.error||{at:m.at,model:m.model,message:m.text,note:'This error was saved by an older Observe version, which did not retain provider diagnostics. Retry with the updated app to capture the cause.'},null,2);modal('Observer error log','<p class="card-note">Provider errors, local checks, request ID and model budgets. API keys and raw evidence are excluded.</p><pre id="observer-error-details">'+esc(observerErrorLog)+'</pre>','<button class="primary" data-action="observer-copy-error">Copy error log</button>');return;}if(b.dataset.copyMessage){const m=observerChat.messages.find(x=>x.id===b.dataset.copyMessage);await request('observer-copy',{text:observerBody(m)||observerProblem(m)});toast('Copied.');return;}
switch(b.dataset.action){
case 'observer-config':observerConfig();break;case 'observer-copy-error':await request('observer-copy',{text:observerErrorLog});toast('Error log copied.');break;
case 'observer-save':await request('observer-save',{key:$('#observer-key').value,model:$('#observer-model').value});$('#observer-key').value='';$('#modal').classList.add('hidden');toast('chatGPT observer enabled.');break;
case 'observer-remove':await request('observer-remove');toast('Plugin removed and API key cleared. Your saved chats are retained.');break;
case 'observer-new':if(observerSending)return;observerChat=null;observerDraft='';observerError='';observerStream='';render();await observerLoad();$('#chat-input').focus();break;
case 'observer-example':$('#chat-input').value=observerExample;observerDraft=observerExample;observerUpdate();$('#chat-input').focus();break;
case 'observer-script-example':$('#chat-input').value='What did C:\\Users\\ExampleUser\\Documents\\observe-test.ps1 do? Explain the recorded file and registry changes.';observerDraft=$('#chat-input').value;observerUpdate();$('#chat-input').focus();break;
case 'observer-stop':await request('observer-cancel');break;
case 'observer-delete':if(!observerChat?.id)return;modal('Delete this chat?',`<p>Delete <strong>${esc(observerChat.title)}</strong> and its saved evidence snapshots from this PC?</p>`,`<button class="primary danger" data-action="observer-delete-confirm">Delete chat</button>`);break;
case 'observer-delete-confirm':await request('observer-delete',{id:observerChat.id});observerChat=null;$('#modal').classList.add('hidden');render();await observerLoad();break;
case 'observer-rename':if(!observerChat?.id)return;modal('Rename chat',`<label class="field">Chat title<input id="chat-title" maxlength="100" value="${esc(observerChat.title)}"></label>`,`<button class="primary" data-action="observer-rename-confirm">Save name</button>`);break;
case 'observer-rename-confirm':observerChat=await request('observer-rename',{id:observerChat.id,title:$('#chat-title').value});$('#modal').classList.add('hidden');await observerLoad();break;
}
}catch(e){toast(e.message,true);}});

function observerModelOptions(){return state.observer.models.map(m=>`<option value="${esc(m.id)}" ${m.id===state.observer.model?'selected':''}>${esc(m.label)}</option>`).join('');}
function observerModelInfo(id){const m=state.observer.models.find(x=>x.id===id);return m?`$${m.inputPrice.toFixed(2)} input / $${m.outputPrice.toFixed(2)} output per 1M tokens · Request cap: ${m.inputBudget.toLocaleString()} input / ${m.outputBudget.toLocaleString()} output. Evidence is automatically shortened to fit.`:'Choose one of the supported models.';}
document.addEventListener('change',async e=>{if(e.target.id==='observer-model')$('#observer-model-info').textContent=observerModelInfo(e.target.value);if(e.target.id==='chat-model'){try{await request('observer-save',{key:'',model:e.target.value});toast('Model updated. The next message will use its token budget.');}catch(error){toast(error.message,true);e.target.value=state.observer.model;}}});
